import type {
  FlagUsage,
  MigrationAnalysis,
  MigrationInventoryItem,
  MigrationItem,
  MigrationManualReviewReason,
  MigrationValueType,
  ScanResult,
} from "../types.js";

declare const __PKG_VERSION__: string;

// ── evidence helpers ─────────────────────────────────────────────────────────

function legacyInventoryFromUsage(usage: FlagUsage): MigrationInventoryItem {
  const isBulk = usage.flagKey === "*" || usage.callType === "allFlags" || usage.callType === "allFlagsState";
  const manualReviewReason: MigrationManualReviewReason | undefined = isBulk
    ? "bulk-inventory-call"
    : usage.isDynamic
      ? "dynamic-key"
      : "unknown-fallback";

  return {
    file: usage.file,
    line: usage.line,
    column: usage.column,
    launchDarklyMethod: usage.callType,
    flagKeyExpression: isBulk ? undefined : usage.isDynamic ? "flagKey" : `'${usage.flagKey}'`,
    staticFlagKey: usage.isDynamic || isBulk ? undefined : usage.flagKey,
    isDynamic: usage.isDynamic,
    valueType: "unknown",
    safelyAutomatable: false,
    manualReviewReason,
  };
}

function inventoryFrom(result: ScanResult): MigrationInventoryItem[] {
  if (result.migrationInventory) return result.migrationInventory;
  return result.usages.map(legacyInventoryFromUsage);
}

function isServerInventoryItem(item: MigrationInventoryItem): boolean {
  return (
    item.launchDarklyMethod === "variation" ||
    item.launchDarklyMethod === "variationDetail" ||
    item.launchDarklyMethod === "boolVariation" ||
    item.launchDarklyMethod === "boolVariationDetail" ||
    item.launchDarklyMethod === "stringVariation" ||
    item.launchDarklyMethod === "stringVariationDetail" ||
    item.launchDarklyMethod === "numberVariation" ||
    item.launchDarklyMethod === "numberVariationDetail" ||
    item.launchDarklyMethod === "jsonVariation" ||
    item.launchDarklyMethod === "jsonVariationDetail" ||
    item.launchDarklyMethod === "allFlags" ||
    item.launchDarklyMethod === "allFlagsState"
  );
}

function openFeatureMethod(valueType: MigrationValueType): string | null {
  switch (valueType) {
    case "boolean":
      return "client.getBooleanValue()";
    case "string":
      return "client.getStringValue()";
    case "number":
      return "client.getNumberValue()";
    case "object":
      return "client.getObjectValue()";
    case "unknown":
      return null;
  }
}

function reasonLabel(reason: MigrationManualReviewReason | undefined): string {
  switch (reason) {
    case "dynamic-key":
      return "dynamic key";
    case "unknown-fallback":
      return "unsupported or unknown fallback";
    case "bulk-inventory-call":
      return "bulk inventory call";
    default:
      return "manual review required";
  }
}

function buildEvidenceItem(item: MigrationInventoryItem): MigrationItem {
  const flagLabel = item.staticFlagKey ?? item.flagKeyExpression ?? "*";
  const beforeArgs = [
    item.flagKeyExpression,
    item.evaluationContextExpression,
    item.fallbackExpression,
  ].filter((value): value is string => Boolean(value));
  const before = `${item.launchDarklyMethod}(${beforeArgs.join(", ")})`;
  const equivalent = item.safelyAutomatable ? openFeatureMethod(item.valueType) : null;

  return {
    usage: {
      flagKey: item.staticFlagKey ?? (item.isDynamic ? "dynamic" : "*"),
      isDynamic: item.isDynamic,
      file: item.file,
      line: item.line,
      column: item.column,
      callType: item.launchDarklyMethod,
      stalenessSignals: [],
    },
    openFeatureEquivalent: equivalent,
    codeChangeBefore: before,
    codeChangeAfter: "// No codemod generated by this report",
    requiresManualReview: !item.safelyAutomatable,
    reviewReason: item.safelyAutomatable ? undefined : reasonLabel(item.manualReviewReason),
  };
}

function calcReadinessScore(items: MigrationInventoryItem[]): number {
  if (items.length === 0) return 0;
  const safeCount = items.filter((item) => item.safelyAutomatable).length;
  const score = Math.round((safeCount / items.length) * 100);
  return safeCount === items.length ? 100 : Math.min(score, 99);
}

function calcRequiredPackages(items: MigrationInventoryItem[]): string[] {
  return items.some(isServerInventoryItem) ? ["@openfeature/server-sdk"] : [];
}

// ── public exports ────────────────────────────────────────────────────────────

export function analyze(result: ScanResult): MigrationAnalysis {
  const inventoryItems = inventoryFrom(result);
  const items = inventoryItems.map(buildEvidenceItem);
  const totalLaunchDarklyUsages = inventoryItems.length;
  const safelyAutomatableCount = inventoryItems.filter((item) => item.safelyAutomatable).length;
  const dynamicKeyCount = inventoryItems.filter((item) => item.manualReviewReason === "dynamic-key").length;
  const bulkInventoryCallCount = inventoryItems.filter(
    (item) => item.manualReviewReason === "bulk-inventory-call"
  ).length;
  const unsupportedUnknownCount = inventoryItems.filter(
    (item) => item.manualReviewReason === "unknown-fallback"
  ).length;
  const manualReviewCount = totalLaunchDarklyUsages - safelyAutomatableCount;
  const autoMigrateCount = safelyAutomatableCount;
  const readinessScore = calcReadinessScore(inventoryItems);
  const requiredPackages = calcRequiredPackages(inventoryItems);

  return {
    readinessScore,
    requiredPackages,
    items,
    inventoryItems,
    totalLaunchDarklyUsages,
    safelyAutomatableCount,
    dynamicKeyCount,
    bulkInventoryCallCount,
    unsupportedUnknownCount,
    manualReviewCount,
    autoMigrateCount,
  };
}

export function formatMigrationReport(analysis: MigrationAnalysis): string {
  const {
    requiredPackages,
    inventoryItems,
    totalLaunchDarklyUsages,
    safelyAutomatableCount,
    manualReviewCount,
    dynamicKeyCount,
    bulkInventoryCallCount,
    unsupportedUnknownCount,
  } = analysis;
  const date = new Date().toLocaleDateString();
  const version = typeof __PKG_VERSION__ !== "undefined" ? __PKG_VERSION__ : "0.1.0";

  const lines: string[] = [];

  lines.push("# OpenFeature Migration Inventory");
  lines.push(`Generated by FlagLint v${version} on ${date}`);
  lines.push("");
  lines.push("## Evidence Summary");
  lines.push(`**Total LaunchDarkly usages found:** ${totalLaunchDarklyUsages}  `);
  lines.push(`**Safely automatable usages:** ${safelyAutomatableCount}  `);
  lines.push(`**Manual review required:** ${manualReviewCount}  `);
  lines.push(`**Dynamic keys:** ${dynamicKeyCount}  `);
  lines.push(`**Bulk inventory calls:** ${bulkInventoryCallCount}  `);
  lines.push(`**Unsupported/unknown cases:** ${unsupportedUnknownCount}`);
  lines.push("");

  if (manualReviewCount > 0) {
    lines.push(
      "> This report is an inventory, not a codemod. Manual-review items must be resolved before treating the migration as safe."
    );
    lines.push("");
  }

  if (requiredPackages.length > 0) {
    lines.push("## OpenFeature Packages To Evaluate");
    lines.push("```");
    lines.push(`npm install ${requiredPackages.join(" ")}`);
    lines.push("```");
    lines.push("");
  }

  const safeItems = inventoryItems.filter((item) => item.safelyAutomatable);
  const manualItems = inventoryItems.filter((item) => !item.safelyAutomatable);

  if (safeItems.length > 0) {
    lines.push("## Safely Automatable Inventory");
    for (const item of safeItems) {
      const flag = item.staticFlagKey ?? item.flagKeyExpression ?? "unknown";
      lines.push(
        `- ${item.file}:${item.line}:${item.column} — \`${flag}\` via \`${item.launchDarklyMethod}\` (${item.valueType})`
      );
      lines.push(
        `  context: \`${item.evaluationContextExpression ?? "unknown"}\`; fallback: \`${item.fallbackExpression ?? "unknown"}\``
      );
    }
    lines.push("");
  }

  if (manualItems.length > 0) {
    lines.push("## Manual Review Required");
    for (const item of manualItems) {
      const flag = item.staticFlagKey ?? item.flagKeyExpression ?? "*";
      lines.push(
        `- ${item.file}:${item.line}:${item.column} — \`${flag}\` via \`${item.launchDarklyMethod}\`: ${reasonLabel(item.manualReviewReason)}`
      );
      if (item.evaluationContextExpression) lines.push(`  context: \`${item.evaluationContextExpression}\``);
      if (item.fallbackExpression) lines.push(`  fallback: \`${item.fallbackExpression}\``);
    }
    lines.push("");
  }

  lines.push("## Resources");
  lines.push("- OpenFeature docs: https://openfeature.dev/docs");
  lines.push("- OpenFeature server SDK: https://openfeature.dev/docs/reference/technologies/server/javascript");
  lines.push("");

  return lines.join("\n");
}
