#!/bin/sh
# Auto-append DCO Signed-off-by line if not already present.
NAME=$(git config user.name)
EMAIL=$(git config user.email)
SOB="Signed-off-by: $NAME <$EMAIL>"
grep -qs "^$SOB" "$1" || printf "\n%s\n" "$SOB" >> "$1"
